name: Lint

on:
  push:
    paths:
      - '.github/workflows/lint.yml'
      - '**.py'
  pull_request:
    paths:
      - '.github/workflows/lint.yml'
      - '**.py'

jobs:
  flake8:
    name: Flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: TrueBrain/actions-flake8@v2
