name: Syntax Tests

on:
  push:
    paths:
      - '.github/workflows/syntax.yml'
      - '**.sublime-syntax'
      - '**/syntax_test*'
      - '**.tmPreferences'
  pull_request:
    paths:
      - '.github/workflows/syntax.yml'
      - '**.sublime-syntax'
      - '**/syntax_test*'
      - '**.tmPreferences'

jobs:
  main:
    name: Syntax Tests (${{ matrix.build }})
    strategy:
      matrix:
        include:
          - build: latest
            packages: master
            continue_on_error: false
          # latest stable build
          - build: 4126
            packages: v4126
            continue_on_error: true
          # earliest stable build supported by the current release branch
          - build: 4107
            packages: v4107
            continue_on_error: true
    continue-on-error: ${{ matrix.continue_on_error }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: SublimeText/syntax-test-action@v2
        with:
          build: ${{ matrix.build }}
          default_packages: ${{ matrix.packages }}
